### ISSUE TITLE
Fetching App Store icons crashes Sketch 42

### ISSUE THREAD

**Issue by sbible** [sagishrieber/sketch-any-icon-fetcher#3]

**Comment by daskaput** [comment]
Any fixes in progress?

**Comment by sagishrieber** [comment]
Hey! Let me check it out this week and I'll try to fix it :)

**Comment by sagishrieber** [comment]
done! :) it works and I added the Clearbit API for fetching logos as well @daskaput @sbible

**Comment by daskaput** [comment]
Thanks so much @sagishrieber - it's one of the most useful plugins out there. Love it!

**Comment by sagishrieber** [comment]
Thanks!! Really appreciate it! :)

**Comment by sbible** [comment]
Awesome, thanks @sagishrieber!
